config/routes.rb
TravelDataCenter::Application.routes.draw do
  root :to => 'home#index'
  resources :hotel_infos  
  get "/home/index"

  authenticated :user do
    root :to => 'home#index'
  end
  
  devise_for :users

  mount RailsAdmin::Engine => '/data', :as => 'rails_admin'
  
  namespace :data do
	root :to  => "data#index"
  end  
  

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :hotel_info, :inverse_of => :address
  attr_accessible :city, :hotel_info_id, :state_name, :street_address, :zipcode, :locate_in
	rails_admin do
		field  :street_address
		field  :locate_in		
		field  :city
		field  :state_name		
		field  :zipcode					
	end	
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :hotel_info, :inverse_of => :contact
  attr_accessible :alternative_phone, :email, :fax, :google_map_url, :hotel_info_id, :phone, :web  
  rails_admin do
		field  :phone
		field  :alternative_phone
		field  :fax		
		field  :email
		field  :web
		field  :google_map_url
	end	
end

app/models/context_rate.rb
class ContextRate < ActiveRecord::Base
  attr_accessible :price
  has_and_belongs_to_many :rooms
  belongs_to :rate, :inverse_of => :context_rates  
  
  has_many :pax_contexts, :dependent => :destroy, :inverse_of => :rate
  attr_accessible :pax_context_ids  
  
  rails_admin do
		field  :price
		field  :pax_context_ids		
	end	
end

app/models/hotel_info.rb
class HotelInfo < ActiveRecord::Base  
  attr_accessible :hotel_status, :latitude, :longitude, :when_built, 
                  :property_type, :segment, :category, :chain, :check_in, :check_out

  has_one :hotel_name, :dependent => :destroy, :inverse_of => :hotel_info    
  attr_accessible :hotel_name_attributes, :allow_destroy => true
  accepts_nested_attributes_for :hotel_name, :allow_destroy => true

  has_one :address, :dependent => :destroy, :inverse_of => :hotel_info
  attr_accessible :address_attributes, :allow_destroy => true
  accepts_nested_attributes_for :address, :allow_destroy => true
  
  has_one :contact, :dependent => :destroy, :inverse_of => :hotel_info
  attr_accessible :contact_attributes, :allow_destroy => true
  accepts_nested_attributes_for :contact, :allow_destroy => true

  has_many :seasons, :dependent => :destroy, :inverse_of => :hotel_info 
  attr_accessible :season_ids

  has_many :rooms, :dependent => :destroy, :inverse_of => :hotel_info
  attr_accessible :room_ids
  
	rails_admin do
		field  :hotel_name
		field  :chain
		field  :category
		field  :property_type
		field  :segment
		field  :hotel_status
		field  :check_in
		field  :check_out
		field  :latitude
		field  :longitude
		field  :when_built		
		field  :rooms
		field  :seasons						
	end	
      
end

app/models/hotel_name.rb
class HotelName < ActiveRecord::Base
  belongs_to :hotel_info, :inverse_of => :hotel_name
  attr_accessible :hotel_info_id, :hotel_short_name, :name, :index_name, :permalink  
  rails_admin do
		field  :name
		field  :hotel_short_name				
		field  :index_name					
		field  :permalink					
	end	
end

app/models/pax.rb
class Pax < ActiveRecord::Base
  attr_accessible :name, :quantity  
  belongs_to :pax_context, :inverse_of => :paxs
  rails_admin do
		field  :name
		field  :quantity						
	end	
end

app/models/pax_context.rb
class PaxContext < ActiveRecord::Base
  belongs_to :context_rate, :inverse_of => :pax_contexts  
  has_many :paxs, :dependent => :destroy, :inverse_of => :pax_context
  attr_accessible :pax_ids, :allow_destroy => true
  rails_admin do
		field  :paxs	
	end	
end

app/models/range_date.rb
class RangeDate < ActiveRecord::Base
  belongs_to :season, :inverse_of => :range_dates  
  has_many :rates, :dependent => :destroy, :inverse_of => :range_date
  attr_accessible :rate_ids 
  attr_accessible :end, :start    
  rails_admin do
		field :start		
		field :end	
		field :rates	
	end	
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  attr_accessible :name  
  belongs_to :range_date,:inverse_of => :rates
  has_many :context_rates, :dependent => :destroy, :inverse_of => :rate  
  attr_accessible :context_rate_ids  
	rails_admin do
		field  :name
		field  :context_rates		
	end	
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :hotel_info, :inverse_of => :rooms
  has_and_belongs_to_many :context_rates
  attr_accessible :hotel_info_id, :name  
  attr_accessible :context_rate_ids    
	rails_admin do
		field  :name
		field  :context_rates		
	end	
end

app/models/season.rb
class Season < ActiveRecord::Base
  belongs_to :hotel_info, :inverse_of => :seasons
  attr_accessible :name
  has_many :range_dates, :dependent => :destroy, :inverse_of => :season 
  attr_accessible :range_date_ids    
  rails_admin do
		field  :name
		field  :range_dates		
	end	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
#  rescue_from CanCan::AccessDenied do |exception|
#    redirect_to root_path, :alert => exception.message
#  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/hotel_info_controller.rb
class HotelInfoController < ApplicationController
	before_filter :authenticate_user!


   # GET /hotel_infos
  # GET /hotel_infos.json
  def index
    @hotel_infos = HotelInfo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @hotel_infos }
    end
  end

end

app/controllers/hotel_infos_controller.rb
class HotelInfosController < ApplicationController
	before_filter :authenticate_user!

  # GET /hotel_infos
  # GET /hotel_infos.json
  def index
    @hotel_infos = HotelInfo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @hotel_infos }
    end
  end

  # GET /hotel_infos
  # GET /hotel_infos.json
  def index_hotels
    @hotel_infos = HotelInfo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @hotel_infos }
    end
  end
  
  # GET /hotel_infos/1
  # GET /hotel_infos/1.json
  def show
    @hotel_info = HotelInfo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @hotel_info }
    end
  end

  # GET /hotel_infos/new
  # GET /hotel_infos/new.json
  def new
    @hotel_info = HotelInfo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @hotel_info }
    end
  end

  # GET /hotel_infos/1/edit
  def edit
    @hotel_info = HotelInfo.find(params[:id])
  end

  # POST /hotel_infos
  # POST /hotel_infos.json
  def create
    @hotel_info = HotelInfo.new(params[:hotel_info])

    respond_to do |format|
      if @hotel_info.save
        format.html { redirect_to @hotel_info, :notice => 'Hotel info was successfully created.' }
        format.json { render :json => @hotel_info, :status => :created, :location => @hotel_info }
      else
        format.html { render :action => "new" }
        format.json { render :json => @hotel_info.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /hotel_infos/1
  # PUT /hotel_infos/1.json
  def update
    @hotel_info = HotelInfo.find(params[:id])

    respond_to do |format|
      if @hotel_info.update_attributes(params[:hotel_info])
        format.html { redirect_to @hotel_info, :notice => 'Hotel info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @hotel_info.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /hotel_infos/1
  # DELETE /hotel_infos/1.json
  def destroy
    @hotel_info = HotelInfo.find(params[:id])
    @hotel_info.destroy

    respond_to do |format|
      format.html { redirect_to hotel_infos_url }
      format.json { head :no_content }
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hotel_info_helper.rb
module HotelInfoHelper
end

app/views/home/index.html.erb
<h3>Welcome to Travel Data Center</h3>

<%= link_to "Data", "/data" %>

app/views/hotel_infos/_depth_level_info.html.haml
%table.table.table-hover.table-condensed.datatable
  - plans = ["CP", "AP", "MAP"]
  %thead
    %tr
      %th Seanson   
      %th Available room types
      %th Persons
      %th Plan
      %th Price
  %body
    - rooms = ["Standard Studio", "Superior Room", "Executive Room", "Deluxe Studio", "One-Bedroom Apartment","Two-Bedroom Apartment", "Suite", "Junior Suite"]
    - seasons = [{"Low"         =>  {:ranges => [{ :start => "01/01/12",:end => "12/21/12"}, 
                                                 { :start => "05/01/13",:end => "07/20/13"}],
                                     :type => 'success'}},
                 {"Medium"      =>  {:ranges => [{ :start => "08/21/13",:end => "10/31/13"}, 
                                                 { :start => "04/01/13",:end => "04/30/13"}],
                                     :type => 'success' }},                                                        
                 {"High"        =>  {:ranges => [{ :start => "07/21/13",:end => "08/24/13"}]}},                  
                 {"Extra high"  =>  [{ :start => "01/03/13",:end => "03/31/13"}]}, 
                 {"Peak"        =>  [{ :start => "07/21/13",:end => "08/24/13"}]}]                                                     
    - for i in 0...seasons.length                                                      
      - colum = 2 + rand(3)
      - 1.upto(colum) do
        - plans.each do |plan|        
          %tr
            %td
              - type_styles = {"Low" => "success","Medium" => "info", "High" => "primary", "Extra high" =>"warning", "Peak" =>"danger"} 
              - key = seasons[i].keys.first 
              %button{:class => "btn btn-#{type_styles[key]} btn-mini"}
                = seasons[i].keys.first           
            %td          
              - room = rooms[rand(7)]
              %a{:href => "#"}
                = room          
            %td
              - paxs = 1 + rand(3)
              - 1.upto(paxs) do
                %i.icon-user.icon-large
              - childs = rand(2)
              - if childs > 0
                +
                - 1.upto(childs) do
                  %i.icon-user
            %td= plan       
            %td 
              = "#{100 + rand(200)} USD"
%br              

app/views/hotel_infos/_form.html.erb
<%= form_for(@hotel_info) do |f| %>
  <% if @hotel_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hotel_info.errors.count, "error") %> prohibited this hotel_info from being saved:</h2>

      <ul>
      <% @hotel_info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hotel_infos/_item_info.html.haml
- @hotel_infos.each do |h|
  - hotel_name = "Hotel #{h.hotel_name.name}"
  %h4{:itemprop => "name"}
    = hotel_name
    - star = 2 + rand(3)
    - 1.upto(star) do
      %i.icon-star
    %br/
    %small.muted
      = Faker::Address.street_address
      %a
        %span Show at map
        %i.icon-map-marker
  %p.hidden-phone
    = truncate(Faker::Lorem.sentence(word_count = 50), :length => 240)

app/views/hotel_infos/edit.html.erb
<h1>Editing hotel_info</h1>

<%= render 'form' %>

<%= link_to 'Show', @hotel_info %> |
<%= link_to 'Back', hotel_infos_path %>

app/views/hotel_infos/index.html.haml
%table.table.table-hover.table-condensed.datatable
  %thead
    %tr
      %th Chain
      %th Name
      %th Category
      %th Type
      %th Segment
      %th City          
      %th Latitude
      %th Longitude    
  %body
  - @hotel_infos.each do |hotel_info|
    %tr
      %td= hotel_info.chain
      %td 
        = link_to(hotel_info.hotel_name.name, :controller => 'hotel_infos', :action => 'show', :id => hotel_info.id) # :name => hotel_info.hotel_name.name
      %td= hotel_info.category.split("estrellas")[0].to_i unless hotel_info.category.nil?
      %td= hotel_info.property_type      
      %td= hotel_info.segment      
      %td= hotel_info.address.city                         
      %td= hotel_info.latitude
      %td= hotel_info.longitude                  
%br/

app/views/hotel_infos/index_hotels.html.haml
- for i in 1..10 #@hotel_infos.each do |h|
  - h = @hotel_infos[i]
  - "#{h.chain}"  
  - hotel_name = "#{h.hotel_name.name}"
  %h4{:itemprop => "name"}
    = hotel_name
    - stars = 0 
    - stars = h.category.split("estrellas")[0].to_i unless h.category.nil?
    - 1.upto(stars) do
      %i.icon-star-empty
  %small.muted
    = h.address.street_address
    %br
    = h.address.city
    %br
    %a
      %span Show at map
      %i.icon-map-marker
  .progress.progress-info.progress-striped
    - star_date = DateTime.new(2012,10,1)
    - date_now = DateTime.now
    - progress_date = (date_now -star_date).to_i
    - progress = (progress_date/365*100).to_i
    %div{:class => "bar", :style => "width: #{77}%;"} 
      %strong 
        Past
  .progress.bar
    - ranges = [{"Low" => 22}, {"Peak" => 18}, {"Extra high" => 10}, {"Medium" => 8}, {"Low" => 31}, {"High" => 11}]
    - type_styles = {"Low" => "success","Medium" => "info", "High" => "default", "Extra high" =>"warning", "Peak" =>"danger"}      
    - for i in 0...ranges.length        
      - value = ranges[i].values[0]
      - key = ranges[i].keys[0]
      - type_style = "default"
      - type_style = type_styles[key] if type_styles[key]
      %div{:class => "bar bar-#{type_style}", :style => "width: #{value}%;"}
        %strong 
          = key
          %a{"data-placement" => "top", :href => "#", :rel => "tooltip", :title => "31/10/12 - 12/01/13"}
            %i.icon-hand-down.icon-white
  %small
    = render 'depth_level_info'
      
   

app/views/hotel_infos/index_temp.html.haml
- @hotel_infos.each do |h|  
  - "#{h.chain}"  
  - hotel_name = "#{h.hotel_name.name}"
  %h4{:itemprop => "name"}
    = hotel_name
    - stars = 0 
    - stars = h.category.split("estrellas")[0].to_i unless h.category.nil?
    - 1.upto(stars) do
      %i.icon-star-empty
  %small.muted
    = h.address.street_address
    %br
    = h.address.city
    %br
    %a
      %span Show at map
      %i.icon-map-marker
  .progress.progress-info.progress-striped
    - star_date = DateTime.new(2012,10,1)
    - date_now = DateTime.now
    - progress_date = (date_now -star_date).to_i
    - progress = (progress_date/365*100).to_i
    %div{:class => "bar", :style => "width: #{77}%;"} 
      %strong 
        Past
  .progress.bar
    - ranges = [{"Low" => 22}, {"Peak" => 18}, {"Extra high" => 10}, {"Medium" => 8}, {"Low" => 31}, {"High" => 11}]
    - type_styles = {"Low" => "success","Medium" => "info", "High" => "default", "Extra high" =>"warning", "Peak" =>"danger"}      
    - for i in 0...ranges.length        
      - value = ranges[i].values[0]
      - key = ranges[i].keys[0]
      - type_style = "default"
      - type_style = type_styles[key] if type_styles[key]
      %div{:class => "bar bar-#{type_style}", :style => "width: #{value}%;"}
        %strong 
          = key
          %a{"data-placement" => "top", :href => "#", :rel => "tooltip", :title => "31/10/12 - 12/01/13"}
            %i.icon-hand-down.icon-white
  %small
    = render 'depth_level_info'
      
   

app/views/hotel_infos/new.html.erb
<h1>New hotel_info</h1>

<%= render 'form' %>

<%= link_to 'Back', hotel_infos_path %>

app/views/hotel_infos/show.html.haml
p#notice= notice
- h = @hotel_info
- "#{h.chain}"  
- hotel_name = "#{h.hotel_name.name}"
%h4{:itemprop => "name"}
	= hotel_name
	- stars = 0 
	- stars = h.category.split("estrellas")[0].to_i unless h.category.nil?
	- 1.upto(stars) do
		%i.icon-star-empty
%small.muted
	= h.address.street_address
	%br
	= h.address.city
	%br
	%a
		%span Show at map
		%i.icon-map-marker
.progress.progress-info.progress-striped
	- star_date = DateTime.new(2012,10,1)
	- date_now = DateTime.now
	- progress_date = (date_now -star_date).to_i
	- progress = (progress_date/365*100).to_i
	%div{:class => "bar", :style => "width: #{77}%;"} 
		%strong 
			Past
.progress.bar
	- ranges = [{"Low" => 22}, {"Peak" => 18}, {"Extra high" => 10}, {"Medium" => 8}, {"Low" => 31}, {"High" => 11}]
	- type_styles = {"Low" => "success","Medium" => "info", "High" => "default", "Extra high" =>"warning", "Peak" =>"danger"}      
	- for i in 0...ranges.length        
		- value = ranges[i].values[0]
		- key = ranges[i].keys[0]
		- type_style = "default"
		- type_style = type_styles[key] if type_styles[key]
		%div{:class => "bar bar-#{type_style}", :style => "width: #{value}%;"}
			%strong 
				= key
				%a{"data-placement" => "top", :href => "#", :rel => "tooltip", :title => "31/10/12 - 12/01/13"}
					%i.icon-hand-down.icon-white
%small
	= render 'depth_level_info'

= link_to 'Edit', edit_hotel_info_path(@hotel_info) 
= link_to 'Back', hotel_infos_path 

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Travel Data Center", root_path, :class => 'brand' %>
<ul class="nav">
  <li>
    <%= link_to 'Hotels Info', :controler => "hotel_info" %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TravelDataCenter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>